// Generated by CoffeeScript 1.12.7
(function() {
  var JSOG, JSOG_OBJECT_ID, hasCustomJsonificaiton, isArray, nextId;

  JSOG = {};

  nextId = 0;

  isArray = Array.isArray || function(obj) {
    return Object.prototype.toString.call(obj) === '[object Array]';
  };

  hasCustomJsonificaiton = function(obj) {
    return obj.toJSON != null;
  };

  JSOG_OBJECT_ID = '__jsogObjectId';

  JSOG.encode = function(original, idProperty, refProperty) {
    var doEncode, idOf, sofar;
    if (idProperty == null) {
      idProperty = '@id';
    }
    if (refProperty == null) {
      refProperty = '@ref';
    }
    sofar = {};
    idOf = function(obj) {
      if (!obj[JSOG_OBJECT_ID]) {
        obj[JSOG_OBJECT_ID] = "" + (nextId++);
      }
      return obj[JSOG_OBJECT_ID];
    };
    doEncode = function(original) {
      var encodeArray, encodeObject;
      encodeObject = function(original) {
        var id, key, obj1, obj2, result, value;
        id = idOf(original);
        if (sofar[id]) {
          return (
            obj1 = {},
            obj1["" + refProperty] = id,
            obj1
          );
        }
        result = sofar[id] = (
          obj2 = {},
          obj2["" + idProperty] = id,
          obj2
        );
        for (key in original) {
          value = original[key];
          if (key !== JSOG_OBJECT_ID) {
            result[key] = doEncode(value);
          }
        }
        return result;
      };
      encodeArray = function(original) {
        var val;
        return (function() {
          var i, len, results;
          results = [];
          for (i = 0, len = original.length; i < len; i++) {
            val = original[i];
            results.push(doEncode(val));
          }
          return results;
        })();
      };
      if (original == null) {
        return original;
      } else if (hasCustomJsonificaiton(original)) {
        return original;
      } else if (isArray(original)) {
        return encodeArray(original);
      } else if (typeof original === 'object') {
        return encodeObject(original);
      } else {
        return original;
      }
    };
    return doEncode(original);
  };

  JSOG.decode = function(encoded, idProperty, refProperty) {
    var doDecode, initObjectsById, objectsById;
    if (idProperty == null) {
      idProperty = '@id';
    }
    if (refProperty == null) {
      refProperty = '@ref';
    }
    objectsById = {};
    initObjectsById = function(encoded) {
      var i, id, key, len, results, results1, value;
      if (encoded == null) {
        return;
      }
      if (isArray(encoded)) {
        results = [];
        for (i = 0, len = encoded.length; i < len; i++) {
          value = encoded[i];
          results.push(initObjectsById(value));
        }
        return results;
      } else if (typeof encoded === 'object') {
        id = encoded[idProperty];
        if (id != null) {
          id = id.toString();
        }
        if (id) {
          objectsById[id] = encoded;
        }
        results1 = [];
        for (key in encoded) {
          value = encoded[key];
          results1.push(initObjectsById(value));
        }
        return results1;
      }
    };
    doDecode = function(encoded) {
      var decodeArray, decodeObject;
      decodeObject = function(encoded) {
        var id, key, obj, process, ref, result, value;
        id = encoded[idProperty];
        ref = encoded[refProperty];
        if (id != null) {
          id = id.toString();
        } else if (ref != null) {
          id = ref.toString();
        }
        if (id != null) {
          obj = objectsById[id];
          process = obj[idProperty] != null;
        } else {
          obj = encoded;
          process = true;
        }
        if (!process) {
          return obj;
        }
        result = {};
        if (id) {
          objectsById[id] = result;
        }
        for (key in obj) {
          value = obj[key];
          if (key !== idProperty) {
            result[key] = doDecode(value);
          }
        }
        return result;
      };
      decodeArray = function(encoded) {
        var value;
        return (function() {
          var i, len, results;
          results = [];
          for (i = 0, len = encoded.length; i < len; i++) {
            value = encoded[i];
            results.push(doDecode(value));
          }
          return results;
        })();
      };
      if (encoded == null) {
        return encoded;
      } else if (isArray(encoded)) {
        return decodeArray(encoded);
      } else if (typeof encoded === 'object') {
        return decodeObject(encoded);
      } else {
        return encoded;
      }
    };
    initObjectsById(encoded);
    return doDecode(encoded);
  };

  JSOG.stringify = function(obj) {
    return JSON.stringify(JSOG.encode(obj));
  };

  JSOG.parse = function(str) {
    return JSOG.decode(JSON.parse(str));
  };

  if ((typeof module !== "undefined" && module !== null) && module.exports) {
    module.exports = JSOG;
  }

  if (typeof window !== "undefined" && window !== null) {
    window.JSOG = JSOG;
  }

  if (typeof define === 'function' && define.amd) {
    define('JSOG', [], function() {
      return JSOG;
    });
  }

  return JSOG;

}).call(this);
